### ISSUE TITLE
error:

### ISSUE THREAD

**Issue by EdricSon** [botbahlul/translatesrt#1]
translatesrt.exe: error: unrecognized arguments: --multiprocessing-fork pipe_handle=1304
usage: translatesrt.exe [-h] [-S SRC_LANGUAGE] [-D DST_LANGUAGE] [-ll] [-F FORMAT] [-lf] [-C CONCURRENCY] [-v]
                        [subtitle_file_path]
usage: translatesrt.exe [-h] [-S SRC_LANGUAGE] [-D DST_LANGUAGE] [-ll] [-F FORMAT] [-lf] [-C CONCURRENCY] [-v]
                        [subtitle_file_path]
usage: translatesrt.exe [-h] [-S SRC_LANGUAGE] [-D DST_LANGUAGE] [-ll] [-F FORMAT] [-lf] [-C CONCURRENCY] [-v]
                        [subtitle_file_path]
translatesrt.exe: error: unrecognized arguments: --multiprocessing-fork pipe_handle=1328
translatesrt.exe: error: unrecognized arguments: --multiprocessing-fork pipe_handle=1132
translatesrt.exe: error: unrecognized arguments: --multiprocessing-fork pipe_handle=336
usage: translatesrt.exe [-h] [-S SRC_LANGUAGE] [-D DST_LANGUAGE] [-ll] [-F FORMAT] [-lf] [-C CONCURRENCY] [-v]
                        [subtitle_file_path]
translatesrt.exe: error: unrecognized arguments: --multiprocessing-fork pipe_handle=552
usage: translatesrt.exe [-h] [-S SRC_LANGUAGE] [-D DST_LANGUAGE] [-ll] [-F FORMAT] [-lf] [-C CONCURRENCY] [-v]
                        [subtitle_file_path]
translatesrt.exe: error: unrecognized arguments: --multiprocessing-fork pipe_handle=1220
usage: translatesrt.exe [-h] [-S SRC_LANGUAGE] [-D DST_LANGUAGE] [-ll] [-F FORMAT] [-lf] [-C CONCURRENCY] [-v]
                        [subtitle_file_path]
translatesrt.exe: error: unrecognized arguments: --multiprocessing-fork pipe_handle=1332
usage: translatesrt.exe [-h] [-S SRC_LANGUAGE] [-D DST_LANGUAGE] [-ll] [-F FORMAT] [-lf] [-C CONCURRENCY] [-v]
                        [subtitle_file_path]
translatesrt.exe: error: unrecognized arguments: --multiprocessing-fork pipe_handle=1404
usage: translatesrt.exe [-h] [-S SRC_LANGUAGE] [-D DST_LANGUAGE] [-ll] [-F FORMAT] [-lf] [-C CONCURRENCY] [-v]
                        [subtitle_file_path]
translatesrt.exe: error: unrecognized arguments: --multiprocessing-fork pipe_handle=1428
usage: translatesrt.exe [-h] [-S SRC_LANGUAGE] [-D DST_LANGUAGE] [-ll] [-F FORMAT] [-lf] [-C CONCURRENCY] [-v]
                        [subtitle_file_path]

**Comment by botbahlul** [comment]
> translatesrt.exe: error: unrecognized arguments: --multiprocessing-fork pipe_handle=1304 usage: translatesrt.exe [-h] [-S SRC_LANGUAGE] [-D DST_LANGUAGE] [-ll] [-F FORMAT] [-lf] [-C CONCURRENCY] [-v] [subtitle_file_path] usage: translatesrt.exe [-h] [-S SRC_LANGUAGE] [-D DST_LANGUAGE] [-ll] [-F FORMAT] [-lf] [-C CONCURRENCY] [-v] [subtitle_file_path] usage: translatesrt.exe [-h] [-S SRC_LANGUAGE] [-D DST_LANGUAGE] [-ll] [-F FORMAT] [-lf] [-C CONCURRENCY] [-v] [subtitle_file_path] translatesrt.exe: error: unrecognized arguments: --multiprocessing-fork pipe_handle=1328 translatesrt.exe: error: unrecognized arguments: --multiprocessing-fork pipe_handle=1132 translatesrt.exe: error: unrecognized arguments: --multiprocessing-fork pipe_handle=336 usage: translatesrt.exe [-h] [-S SRC_LANGUAGE] [-D DST_LANGUAGE] [-ll] [-F FORMAT] [-lf] [-C CONCURRENCY] [-v] [subtitle_file_path] translatesrt.exe: error: unrecognized arguments: --multiprocessing-fork pipe_handle=552 usage: translatesrt.exe [-h] [-S SRC_LANGUAGE] [-D DST_LANGUAGE] [-ll] [-F FORMAT] [-lf] [-C CONCURRENCY] [-v] [subtitle_file_path] translatesrt.exe: error: unrecognized arguments: --multiprocessing-fork pipe_handle=1220 usage: translatesrt.exe [-h] [-S SRC_LANGUAGE] [-D DST_LANGUAGE] [-ll] [-F FORMAT] [-lf] [-C CONCURRENCY] [-v] [subtitle_file_path] translatesrt.exe: error: unrecognized arguments: --multiprocessing-fork pipe_handle=1332 usage: translatesrt.exe [-h] [-S SRC_LANGUAGE] [-D DST_LANGUAGE] [-ll] [-F FORMAT] [-lf] [-C CONCURRENCY] [-v] [subtitle_file_path] translatesrt.exe: error: unrecognized arguments: --multiprocessing-fork pipe_handle=1404 usage: translatesrt.exe [-h] [-S SRC_LANGUAGE] [-D DST_LANGUAGE] [-ll] [-F FORMAT] [-lf] [-C CONCURRENCY] [-v] [subtitle_file_path] translatesrt.exe: error: unrecognized arguments: --multiprocessing-fork pipe_handle=1428 usage: translatesrt.exe [-h] [-S SRC_LANGUAGE] [-D DST_LANGUAGE] [-ll] [-F FORMAT] [-lf] [-C CONCURRENCY] [-v] [subtitle_file_path]

Please show exactly what command you just typed, a screenshot will be better
